Vagrant.configure("2") do |config|
  # Configurations common to all VMs
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "coa-controller" do |vm1|
    vm1.vm.network :forwarded_port, guest: 22, host: 12223, id: 'ssh'
    vm1.vm.network "private_network", ip: "10.0.114.11", name: "coa-host"
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.hostname = "coa-controller"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "coa-controller"
      vb.memory = "10000"
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nic3", "natnetwork"]
      vb.customize ["modifyvm", :id, "--nat-network3", "coa-nat"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end
  config.vm.define "coa-compute" do |vm2|
    vm2.vm.network :forwarded_port, guest: 22, host: 12223, id: 'ssh'
    vm2.vm.network "private_network", ip: "10.0.114.12", name: "coa-host"
    vm2.vm.network "private_network", type: "dhcp"
    vm2.vm.hostname = "coa-compute"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "coa-compute"
      vb.memory = "8196"
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--nic3", "natnetwork"]
      vb.customize ["modifyvm", :id, "--nat-network3", "coa-nat"]
      vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end
end
